insert into city (name) values ('Goya');
insert into city (name) values ('Santa Fe');
insert into city (name) values ('Bella Vista');
insert into city (name) values ('Santa Lucía');
insert into city (name) values ('Corrientes');
insert into city (name) values ('Resistencia');

insert into employee (name, last_name, city_id, hiring_date) values ('Alejandro', 'Fernández', 1, '2019-10-12');
insert into employee (name, last_name, city_id, hiring_date) values ('Alejandro', 'Pérez', 2, '2019-02-10');
insert into employee (name, last_name, city_id, hiring_date) values ('Luciano', 'Zini', 2, '2019-02-12');
insert into employee (name, last_name, city_id, hiring_date) values ('Daniela', 'Fernández', 1, '2019-02-20');
insert into employee (name, last_name, city_id, hiring_date) values ('Marcela', 'Fernández', 1, '2020-10-03');
insert into employee (name, last_name, city_id, hiring_date) values ('Jesús', 'Zini', 3, '2020-10-05');
insert into employee (name, last_name, city_id, hiring_date) values ('Horacio', 'Zini', 1, '2020-11-11');
insert into employee (name, last_name, city_id, hiring_date) values ('Alejandro', 'Pérez', 3, '2020-12-18');
insert into employee (name, last_name, city_id, hiring_date) values ('Marcelo', 'Gómez', 1, '2019-04-12');
insert into employee (name, last_name, city_id, hiring_date) values ('Lucía', 'Gómez', 4, '2019-06-15');
insert into employee (name, last_name, city_id, hiring_date) values ('María', 'Hernández', 4, '2019-08-12');
insert into employee (name, last_name, city_id, hiring_date) values ('Marcos', 'Hernández', 4, '2019-08-10');
insert into employee (name, last_name, city_id, hiring_date) values ('Fernando', 'Fernández', 5, '2021-10-16');
insert into employee (name, last_name, city_id, hiring_date) values ('Claudio', 'Zini', 5, '2021-01-12');
insert into employee (name, last_name, city_id, hiring_date) values ('Roberto', 'Aguirre', 5, '2021-02-09');
insert into employee (name, last_name, city_id, hiring_date) values ('Claudia', 'Aguirre', 5, '2021-02-10');
insert into employee (name, last_name, city_id, hiring_date) values ('Darío', 'Gómez', 1, '2021-03-01');
insert into employee (name, last_name, city_id, hiring_date) values ('Lisandro', 'Fernández', 6, '2021-03-12');
insert into employee (name, last_name, city_id, hiring_date) values ('Juan', 'Hernández', 2, '2019-05-17');
insert into employee (name, last_name, city_id, hiring_date) values ('Valeria', 'Fernández', 6, '2019-05-23');
insert into employee (name, last_name, city_id, hiring_date) values ('Belén', 'Zini', 6, '2019-05-25');
insert into employee (name, last_name, city_id, hiring_date) values ('Lautaro', 'Gómez', 6, '2020-05-14');
insert into employee (name, last_name, city_id, hiring_date) values ('Laura', 'Aguirre', 2, '2020-05-15');
insert into employee (name, last_name, city_id, hiring_date) values ('Juan', 'Pérez', 2, '2020-05-16');
insert into employee (name, last_name, city_id, hiring_date) values ('María', 'Pérez', 2, '2020-06-12');
insert into employee (name, last_name, city_id, hiring_date) values ('Roberto', 'Fernández', 2, '2020-06-13');
insert into employee (name, last_name, city_id, hiring_date) values ('Alejandro', 'Zini', 3, '2021-07-05');
insert into employee (name, last_name, city_id, hiring_date) values ('Julián', 'Zini', 3, '2021-10-06');
insert into employee (name, last_name, city_id, hiring_date) values ('Marcela', 'Fernández', 4, '2021-12-12');
insert into employee (name, last_name, city_id, hiring_date) values ('Daniela', 'Fernández', 4, '2021-12-23');
insert into employee (name, last_name, city_id, hiring_date) values ('Luciano', 'Gómez', 5, '2020-04-21');
insert into employee (name, last_name, city_id, hiring_date) values ('Juan', 'Gómez', 5, '2020-05-23');
insert into employee (name, last_name, city_id, hiring_date) values ('Roberto', 'Aguirre', 5, '2020-05-12');
insert into employee (name, last_name, city_id, hiring_date) values ('Lucía', 'Pereira', 6, '2020-09-12');
insert into employee (name, last_name, city_id, hiring_date) values ('Juan', 'Pereira', 3, '2021-04-18');
insert into employee (name, last_name, city_id, hiring_date) values ('Lisandro', 'Fernández', 2, '2021-04-17');
insert into employee (name, last_name, city_id, hiring_date) values ('Alejandro', 'Zini', 2, '2022-01-16');
insert into employee (name, last_name, city_id, hiring_date) values ('Julian', 'Fernández', 3, '2022-02-15');
insert into employee (name, last_name, city_id, hiring_date) values ('Valeria', 'Pereira', 2, '2022-02-12');
insert into employee (name, last_name, city_id, hiring_date) values ('Valeria', 'Fernández', 6, '2022-02-18');